spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:h2:mem:movieApiDB  # H2 database
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update  # Automatically update the schema on startup
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true  # Enable the H2 console under /h2-console
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: fayaz.sk224@gmail.com
    password: ycwinezdqjochdro  # App Password
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          timeout: 30000  # 30 sec
          auth: true   # Enable authentication
          starttls:
            enable: true
            required: true
        mime:
          charset: UTF
    verify:
      host: http://localhost:8080

project:
  poster: posters/

base:
  url: http://localhost:8080
